// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package learningmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class Java_action_add extends CustomJavaAction<java.lang.Long>
{
	private java.lang.Long Number1;
	private java.lang.Long Number2;

	public Java_action_add(IContext context, java.lang.Long Number1, java.lang.Long Number2)
	{
		super(context);
		this.Number1 = Number1;
		this.Number2 = Number2;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		long sum = Number1 + Number2;
		System.out.println("Sum is " + sum);
		return sum;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Java_action_add";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
