// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tcconnector.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import tcconnector.internal.foundation.Constants;

public class __SSOCallBackRequest extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String contextPath;

	public __SSOCallBackRequest(IContext context, java.lang.String contextPath)
	{
		super(context);
		this.contextPath = contextPath;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		SSORedirectRequestHandler requestHandler = new SSORedirectRequestHandler(contextPath);
		Core.addRequestHandler(contextPath, requestHandler);
		Constants.LOGGER.info("Registered SSO request handler at context path: " + contextPath);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "__SSOCallBackRequest";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
