// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tcconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import tcconnector.foundation.TcConnection;
import tcconnector.internal.foundation.Constants;
import tcconnector.proxies.ServiceResponse;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * SOA URL:
 * Cad-2007-01-StructureManagement/closeBOMWindows
 * 
 * Description: 
 * Closes a BOMWindow. Must be used to close the BOMWindow created during Create BOM Window after calls to Expand Product Structure services are complete.
 * 
 * Returns:
 * Partial errors can be retrieved using association TcConnector.ResponseData/TcConnector.PartialErrors.
 */
public class CloseBOMWindows extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __InputEntity;
	private tcconnector.proxies.CloseBOMWindowslInput InputEntity;
	private java.lang.String BusinessObjectMappings;
	private java.lang.String ConfigurationName;

	public CloseBOMWindows(IContext context, IMendixObject InputEntity, java.lang.String BusinessObjectMappings, java.lang.String ConfigurationName)
	{
		super(context);
		this.__InputEntity = InputEntity;
		this.BusinessObjectMappings = BusinessObjectMappings;
		this.ConfigurationName = ConfigurationName;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.InputEntity = this.__InputEntity == null ? null : tcconnector.proxies.CloseBOMWindowslInput.initialize(getContext(), __InputEntity);

		// BEGIN USER CODE
		ServiceResponse response = new ServiceResponse(getContext());
		response = (ServiceResponse) TcConnection.callTeamcenterService(getContext(),
				Constants.OPERATION_CLOSEBOMWINDOWS, InputEntity.getMendixObject(), response, SERVICE_OPERATION_MAP,
				BusinessObjectMappings, ConfigurationName, true);
		return response.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CloseBOMWindows";
	}

	// BEGIN EXTRA CODE
	private static final String SERVICE_OPERATION_MAP = "OperationMapping/Cad/2007-01/StructureManagement/closeBOMWindows.json";
	// END EXTRA CODE
}
