// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tcconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import tcconnector.foundation.TcConnection;
import tcconnector.internal.foundation.Constants;
import tcconnector.proxies.CreateWorkflowResponse;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * SOA URL: 
 * Workflow-2014-10-Workflow/createWorkflow
 * 
 * Description:
 * This actions relates a workflow process given the process template name, workflow owner, responsible party, attachments and attachment types.
 * Returns:
 * An entity of type CreateWorkflowResponse. WorkflowTask can be retrieved using association TcConnector.workflowTask.Partial errors can be retrieved using association TcConnector.ResponseData/TcConnector.PartialErrors.
 */
public class CreateWorkflow extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __InputData;
	private tcconnector.proxies.CreateWorkflowInput InputData;
	private java.lang.String BusinessObjectMappings;
	private java.lang.String ConfigurationName;

	public CreateWorkflow(IContext context, IMendixObject InputData, java.lang.String BusinessObjectMappings, java.lang.String ConfigurationName)
	{
		super(context);
		this.__InputData = InputData;
		this.BusinessObjectMappings = BusinessObjectMappings;
		this.ConfigurationName = ConfigurationName;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.InputData = this.__InputData == null ? null : tcconnector.proxies.CreateWorkflowInput.initialize(getContext(), __InputData);

		// BEGIN USER CODE
		CreateWorkflowResponse response = new CreateWorkflowResponse(getContext());
		response = (CreateWorkflowResponse) TcConnection.callTeamcenterService(getContext(),
				Constants.OPERATION_CREATEWORKFLOW, InputData.getMendixObject(), response, SERVICE_OPERATION_MAP,
				BusinessObjectMappings, ConfigurationName, true);
		return response.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateWorkflow";
	}

	// BEGIN EXTRA CODE
	private static final String SERVICE_OPERATION_MAP = "OperationMapping/Workflow/2014-10/Workflow/createWorkflow.json";
	// END EXTRA CODE
}
