// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tcconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import tcconnector.foundation.TcConnection;
import tcconnector.internal.foundation.Constants;
import tcconnector.proxies.ExpandPSAllLevelsResponse;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * SOA URL:
 * Cad-2007-01-StructureManagement/expandPSAllLevels
 * 
 * Description:
 * This actions finds the chilren at all levels given parent bomline. 
 * 
 * Returns:
 * An entity of type ExpandPSAllLevelsResponse. Expanded child bomlines with respective parents can be retrieved using association TcConnector.ExpandPSAllLevelsOutput. Partial errors can be retrieved using association TcConnector.ResponseData/TcConnector.PartialErrors.
 */
public class ExpandPSAllLevels extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __InputEntity;
	private tcconnector.proxies.ExpandPSOneLevelInput InputEntity;
	private java.lang.String BusinessObjectMappings;
	private java.lang.String ConfigurationName;
	private java.lang.Boolean populateServiceDataObjects;

	public ExpandPSAllLevels(IContext context, IMendixObject InputEntity, java.lang.String BusinessObjectMappings, java.lang.String ConfigurationName, java.lang.Boolean populateServiceDataObjects)
	{
		super(context);
		this.__InputEntity = InputEntity;
		this.BusinessObjectMappings = BusinessObjectMappings;
		this.ConfigurationName = ConfigurationName;
		this.populateServiceDataObjects = populateServiceDataObjects;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.InputEntity = this.__InputEntity == null ? null : tcconnector.proxies.ExpandPSOneLevelInput.initialize(getContext(), __InputEntity);

		// BEGIN USER CODE
		ExpandPSAllLevelsResponse response = new ExpandPSAllLevelsResponse(getContext());
		response = (ExpandPSAllLevelsResponse) TcConnection.callTeamcenterService(getContext(),
				Constants.OPERATION_EXPANDPSALLLEVELS, InputEntity.getMendixObject(), response, SERVICE_OPERATION_MAP,
				BusinessObjectMappings, ConfigurationName, populateServiceDataObjects);
		return response.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExpandPSAllLevels";
	}

	// BEGIN EXTRA CODE
	private static final String SERVICE_OPERATION_MAP = "OperationMapping/Cad/2007-01/StructureManagement/expandPSAllLevels.json";
	// END EXTRA CODE
}
