// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tcconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import tcconnector.foundation.TcConnection;
import tcconnector.internal.foundation.Constants;
import tcconnector.proxies.FindSavedQueryResponse;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * SOA URL:
 * Query-2010-04-SavedQuery/findSavedQueries
 * 
 * Description: 
 * This is a generic action finds the saved queries of interest by passing in the criteria such as query name and description. The input for find saved queries is passed through FindSavedQueryInput entity.This operation returns the queries matching the input criteria names and descriptions.
 * 
 * Returns:
 * An entity of type FindSavedQueryResponse. Saved Queries can be retrieved using association TcConnector.savedQueries. Partial errors can be retrieved using association TcConnector.ResponseData/TcConnector.PartialErrors.
 */
public class FindSavedQueries extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __InputData;
	private tcconnector.proxies.FindSavedQueryInput InputData;
	private java.lang.String BusinessObjectMappings;
	private java.lang.String ConfigurationName;

	public FindSavedQueries(IContext context, IMendixObject InputData, java.lang.String BusinessObjectMappings, java.lang.String ConfigurationName)
	{
		super(context);
		this.__InputData = InputData;
		this.BusinessObjectMappings = BusinessObjectMappings;
		this.ConfigurationName = ConfigurationName;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.InputData = this.__InputData == null ? null : tcconnector.proxies.FindSavedQueryInput.initialize(getContext(), __InputData);

		// BEGIN USER CODE
		FindSavedQueryResponse response = new FindSavedQueryResponse(getContext());
		response = (FindSavedQueryResponse) TcConnection.callTeamcenterService(getContext(),
				Constants.OPERATION_FINDSAVEDQUERIES, InputData.getMendixObject(), response, SERVICE_OPERATION_MAP,
				BusinessObjectMappings, ConfigurationName, true);
		return response.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "FindSavedQueries";
	}

	// BEGIN EXTRA CODE
	private static final String SERVICE_OPERATION_MAP = "OperationMapping/Query/2010-04/SavedQuery/findSavedQueries.json";
	// END EXTRA CODE
}
