// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tcconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.thirdparty.org.json.JSONArray;
import com.mendix.thirdparty.org.json.JSONObject;
import com.mendix.webui.CustomJavaAction;
import tcconnector.foundation.BusinessObjectMappings;
import tcconnector.foundation.JModelObject;
import tcconnector.foundation.TcConnection;
import tcconnector.internal.foundation.Constants;
import tcconnector.internal.foundation.ServiceMapper;
import tcconnector.proxies.ListOfValues;

/**
 * SOA URL:
 * Core-2007-06-LOV/getAttachedLOVs
 * 
 * Desciption:
 * Get attached LOV based on input type name and property names structure. The LOV object is returned in the response and service data.
 * 
 * Returns:
 * LOV Entity
 * 
 */
public class GetAttachedLOV extends CustomJavaAction<IMendixObject>
{
	private java.lang.String typeName;
	private java.lang.String propertyName;
	private java.lang.String configurationName;

	public GetAttachedLOV(IContext context, java.lang.String typeName, java.lang.String propertyName, java.lang.String configurationName)
	{
		super(context);
		this.typeName = typeName;
		this.propertyName = propertyName;
		this.configurationName = configurationName;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		ListOfValues lov = new ListOfValues(getContext());
		if (configurationName == null || configurationName.equals("") || configurationName.isEmpty()) {
			configurationName = tcconnector.proxies.microflows.Microflows
					.retrieveConfigNameFromSingleActiveConfiguration(getContext());
			if (configurationName.isEmpty())
				return null;
		}

		String businessObjectMappings = "ListOfValues=TcConnector.ListOfValues";
		ServiceMapper serviceMapper = new ServiceMapper(getContext(), Constants.OPERATION_GET_ATTACHED_LOVS,
				SERVICE_OPERATION_MAP, businessObjectMappings, configurationName);

		// Create body for getAttachedLOVs SOA request
		JSONObject typeInfoInput = new JSONObject();
		typeInfoInput.put("typeName", typeName);
		JSONArray propNameArrayInput = new JSONArray();
		propNameArrayInput.put(propertyName);
		typeInfoInput.put("propNames", propNameArrayInput);
		JSONArray inputArray = new JSONArray();
		inputArray.put(typeInfoInput);
		JSONObject jsonInputObj = new JSONObject();
		jsonInputObj.put("inputs", inputArray);

		JSONObject jsonPolicy = serviceMapper.getObjectPropertyPolicy();
		JSONObject jsonResponseObj = TcConnection.callTeamcenterService(getContext(),
				Constants.OPERATION_GET_ATTACHED_LOVS, jsonInputObj, jsonPolicy, configurationName);
		JSONObject typeNameToLOV = (JSONObject) jsonResponseObj.get("inputTypeNameToLOVOutput");
		JSONArray propLOVInfoArray = (JSONArray) typeNameToLOV.get(typeName);
		if (propLOVInfoArray != null && propLOVInfoArray.length() > 0) {
			JSONObject lovObj = (JSONObject) ((JSONObject) propLOVInfoArray.get(0)).get("lov");
			if (lovObj instanceof JModelObject) {
				JModelObject jModelObj = (JModelObject) lovObj;
				BusinessObjectMappings boMappings = new BusinessObjectMappings(businessObjectMappings,
						configurationName);
				return jModelObj.instantiateEntity(getContext(), "ListOfValues", boMappings, configurationName);
			}
		}
		return lov.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetAttachedLOV";
	}

	// BEGIN EXTRA CODE
	private static final String SERVICE_OPERATION_MAP = "OperationMapping/Core/2007-06/LOV/getAttachedLOVs.json";
	// END EXTRA CODE
}
