// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tcconnector.actions;

import java.util.ArrayList;
import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import tcconnector.foundation.TcConnection;
import tcconnector.internal.foundation.Constants;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.thirdparty.org.json.JSONArray;
import com.mendix.thirdparty.org.json.JSONObject;

/**
 * SOA URL:
 * Core-2007-06-DataManagement/getDatasetTypeInfo
 * 
 * Returns list of NamedReference names applicable for given Dataset Type. This NamedReference names is required while creating a dataset.
 * 
 * Input -
 * - Dataset Type
 * 
 * Output -
 * - List of valid NamedReference names for the input Dataset Type
 */
public class GetFileTypesForDatasetType extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String dataset_type;
	private java.lang.String ConfigurationName;

	public GetFileTypesForDatasetType(IContext context, java.lang.String dataset_type, java.lang.String ConfigurationName)
	{
		super(context);
		this.dataset_type = dataset_type;
		this.ConfigurationName = ConfigurationName;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		List<IMendixObject> iMendixObjectList = new ArrayList<IMendixObject>();

		try {
			// retrive dataset type information like extension
			JSONObject getDatasetTypeInfoResponse = getDatasetTypeInfo();
			JSONArray infosJA = getDatasetTypeInfoResponse.getJSONArray("infos");
			JSONArray refInfosJA = infosJA.getJSONObject(0).getJSONArray("refInfos");

			for (int i = 0; i < refInfosJA.length(); i++) {
				JSONObject refInfoJO = refInfosJA.getJSONObject(i);
				IMendixObject refIno = Core.instantiate(getContext(), tcconnector.proxies.Pair.entityName);
				refIno.setValue(getContext(), "Name", refInfoJO.getString("fileExtension"));
				refIno.setValue(getContext(), "Value", refInfoJO.getString("referenceName"));
				iMendixObjectList.add(refIno);
			}
		} catch (Exception e) {
			String message = "Retrieving available file types for dataset '" + dataset_type + "' failed."
					+ "Please contact your system administrator for further assistance.";
			Constants.LOGGER.error(message + e.getMessage());
			throw e;
		}
		return iMendixObjectList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetFileTypesForDatasetType";
	}

	// BEGIN EXTRA CODE

	private static String createServiceInput(String jsonTemplate, ArrayList<String> substitutions) {
		for (int i = 0; i < substitutions.size(); i++) {
			String replacement = substitutions.get(i);
			String target = "{" + (i + 1) + "}";
			jsonTemplate = jsonTemplate.replace(target, replacement);
		}
		return jsonTemplate;
	}

	private ArrayList<String> createSubstitutionsFor_getDatasetTypeInfo() {
		ArrayList<String> Substitutions = new java.util.ArrayList<String>();
		Substitutions.add(dataset_type);
		return Substitutions;
	}

	private JSONObject getDatasetTypeInfo() throws Exception {
		// getAvailableTypesWithDisplayNames JSON Template
		String getDatasetTypeInfoJT = "{\r\n" + "        \"datasetTypeNames\": [\r\n" + "             \"{1}\"\r\n"
				+ "             ]\r\n" + "            }\r\n" + "    }";
		// substitutions for createDatasets
		ArrayList<String> Substitutions = createSubstitutionsFor_getDatasetTypeInfo();
		getDatasetTypeInfoJT = createServiceInput(getDatasetTypeInfoJT, Substitutions);

		return TcConnection.callTeamcenterService(getContext(), Constants.OPERATION_GETDATASETTYPEINFO,
				getDatasetTypeInfoJT, new JSONObject(), ConfigurationName);
	}
	// END EXTRA CODE
}
