// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tcconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import tcconnector.foundation.TcConnection;
import tcconnector.internal.foundation.Constants;
import tcconnector.proxies.GetLOVValuesResponse;

/**
 * SOA URL:
 * Core-2013-05-LOV/getNextLOVValues
 * 
 * Description:
 * This activity is invoked after a call to GetInitialLOVValues if the moreValuesExist flag is true in the GetLOVValuesResponse Entity returned from a call to the GetInitialLOVValues activity. The activity will retrieve the next set of LOV values.
 * 
 * Returns:
 * LOV Search Results (GetLOVValuesResponse entity instance). Response contains LOV metadata information (LOV usage, LOV style, etc.). It also contains the instance data (LOV values) that the client can use to render the LOV UI widget. The output also contains information as to whether there are more results to be processed in which case a user can page to get next set of values (this triggers a call to the subsequent GetNextLOVValues activity).
 * 
 * For sample usage, kindly download and refer to latest version of 'Teamcenter Connector Sample Application'
 */
public class GetNextLOVValues extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __lovDataEntity;
	private tcconnector.proxies.LOVDataEntity lovDataEntity;
	private java.lang.String configurationName;

	public GetNextLOVValues(IContext context, IMendixObject lovDataEntity, java.lang.String configurationName)
	{
		super(context);
		this.__lovDataEntity = lovDataEntity;
		this.configurationName = configurationName;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.lovDataEntity = this.__lovDataEntity == null ? null : tcconnector.proxies.LOVDataEntity.initialize(getContext(), __lovDataEntity);

		// BEGIN USER CODE
		GetLOVValuesResponse response = new GetLOVValuesResponse(getContext());
		response = (GetLOVValuesResponse) TcConnection.callTeamcenterService(getContext(),
				Constants.OPERATION_GET_NEXT_LOV_VALUES, lovDataEntity.getMendixObject(), response,
				SERVICE_OPERATION_MAP, null, configurationName, true);
		return response.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetNextLOVValues";
	}

	// BEGIN EXTRA CODE
	private static final String SERVICE_OPERATION_MAP = "OperationMapping/Core/2013-05/LOV/getNextLOVValues.json";
	// END EXTRA CODE
}
