// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tcconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import tcconnector.foundation.TcConnection;
import tcconnector.internal.foundation.Constants;
import tcconnector.proxies.TcServerInformation;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * SOA URL: 
 * Core-2007-01-Session/getTCSessionInfo
 * 
 * Description:
 * Retrieves information about the Teamcenter Server session.
 */
public class GetTcSessionInformation extends CustomJavaAction<IMendixObject>
{
	private java.lang.String businessObjectMapping;
	private java.lang.String ConfigurationName;

	public GetTcSessionInformation(IContext context, java.lang.String businessObjectMapping, java.lang.String ConfigurationName)
	{
		super(context);
		this.businessObjectMapping = businessObjectMapping;
		this.ConfigurationName = ConfigurationName;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		TcServerInformation response = new TcServerInformation(getContext());

		response = (TcServerInformation) TcConnection.callTeamcenterService(getContext(),
				Constants.OPERATION_GETSESSIONINFO, null, response, SERVICE_OPERATION_MAP, businessObjectMapping,
				ConfigurationName, true);
		return response.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTcSessionInformation";
	}

	// BEGIN EXTRA CODE
	private static final String SERVICE_OPERATION_MAP = "OperationMapping/Core/2007-01/Session/getTCSessionInfo.json";
	// END EXTRA CODE
}
