// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tcconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import tcconnector.foundation.TcConnection;
import tcconnector.internal.foundation.Constants;
import tcconnector.proxies.SearchResponse;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * SOA URL: 
 * Query-2014-11-Finder/performSearch
 * 
 * Description: 
 * This is a generic action to send the request to and receive the response from a the data provider. It routes search request to a specific provider specified as providerName in the searchInput, assuming the searchCriteria for the provider is represented in the searchCriteriaInput object e.g. 'Awp0SavedQuerySearchProvider' is provider that is used for general search. The input criteria for GeneralSearch is passed through the searchCriteriaInput object.
 * 
 * Returns:
 * An entity of type SearchResponse. Search Results can be retrieved using association TcConnector.searchResultsList. Partial errors can be retrieved using association TcConnector.ResponseData/TcConnector.PartialErrors.
 */
public class PerformSearch extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __InputData;
	private tcconnector.proxies.SearchInput InputData;
	private java.lang.String BusinessObjectMappings;
	private java.lang.String ConfigurationName;

	public PerformSearch(IContext context, IMendixObject InputData, java.lang.String BusinessObjectMappings, java.lang.String ConfigurationName)
	{
		super(context);
		this.__InputData = InputData;
		this.BusinessObjectMappings = BusinessObjectMappings;
		this.ConfigurationName = ConfigurationName;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.InputData = this.__InputData == null ? null : tcconnector.proxies.SearchInput.initialize(getContext(), __InputData);

		// BEGIN USER CODE
		SearchResponse response = new SearchResponse(getContext());
		response = (SearchResponse) TcConnection.callTeamcenterService(getContext(), Constants.OPERATION_PERFORMSEARCH,
				InputData.getMendixObject(), response, SERVICE_OPERATION_MAP, BusinessObjectMappings,
				ConfigurationName, true);
		return response.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PerformSearch";
	}

	// BEGIN EXTRA CODE
	private static final String SERVICE_OPERATION_MAP = "OperationMapping/Query/2014-11/Finder/performSearch.json";
	// END EXTRA CODE
}
